/** Mirrors backend `constants/permissions` — for role & user UIs. */
export const PERMISSION_LABELS: Record<string, string> = {
  'products.viewCostPrice': 'View product cost price (products page only)',
  'admin.access': 'Full administrator access (all areas — see backend)',
  'roles.manage': 'Create and edit roles',
  'doctors.assign': 'Reassign territory / rep / target / tier on a doctor',
  'doctorLocations.review': 'Approve or reject rep-submitted doctor GPS locations',
  'team.view': 'See "My Team" widget and direct reports',
  'team.manage': 'Set / change managerId, territoryId, employeeCode on users',
  'team.viewAllReports': 'See plans, visits, and sales for entire reporting subtree',
  'territories.view': 'View Zones / Areas / Bricks',
  'territories.manage': 'Create / edit / delete Zones / Areas / Bricks',
  'weeklyPlans.review': 'Open submitted weekly plans of direct reports',
  'weeklyPlans.approve': 'Approve or reject submitted weekly plans',
  'callPoints.view': 'View CP (call point) master list',
  'callPoints.create': 'Create CPs',
  'callPoints.edit': 'Edit / activate / deactivate CPs',
  'callPoints.delete': 'Delete CPs (when not referenced by a weekly plan)',
  'expenses.approve': 'Approve field expenses submitted by the team',
  'expenses.reject': 'Reject field expenses submitted by the team',
  'procurement.return': 'Record purchase returns against posted receipts',
  'procurement.grnReverse': 'Reverse a posted goods receipt (emergency / admin)',
  'procurement.cancelPo': 'Cancel supplier orders that have no receipts',
  'attendance.viewTeam': 'View team attendance reports and today board (with attendance.view)',
  'attendance.approve': 'Approve attendance requests (covers direct and escalated inbox actions)',
  'attendance.viewEscalations': "View today's attendance exception summaries (late / open checkout)",
  'attendance.override': 'Mark absent or set today status without full administrator role',
  'reports.accounting': 'Advanced accounting reports (trial balance, P&L, books)',
  'payments.view': 'View money accounts, collections & settlements',
  'payments.create': 'Record collections & settlements',
  'ledger.view': 'View client, supplier, employee & customer ledgers',
  'accounts.view': 'View chart of accounts / financial structure',
  'accounts.manage': 'Manage accounts and opening balances',
  'vouchers.view': 'View financial transactions (vouchers)',
  'vouchers.create': 'Create manual GL entries (accountant)',
  'vouchers.transfer': 'Voucher entry (transfer between money accounts)',
  'vouchers.post': 'Post draft vouchers to the general ledger',
  'vouchers.reverse': 'Reverse posted transactions',
  'deviceControl.manage': 'Manage mobile device control (bindings, change requests, force revoke)',
  'brands.view': 'View product brands',
  'brands.create': 'Create product brands',
  'brands.edit': 'Edit product brands',
  'brands.delete': 'Delete product brands',
  'productTaxonomy.view': 'View product taxonomy (Therapy / Area / Class)',
  'productTaxonomy.manage': 'Create / edit / delete product taxonomy nodes',
  'presentations.view': 'View product detailing presentations',
  'presentations.edit': 'Create and edit presentation slides',
  'presentations.publish': 'Publish presentations for field force',
  'campaigns.view': 'View catalog marketing campaigns',
  'campaigns.create': 'Create catalog campaigns',
  'campaigns.edit': 'Edit catalog campaigns',
  'campaigns.delete': 'Delete catalog campaigns',
  'kits.view': 'View product kits / bundles',
  'kits.create': 'Create product kits',
  'kits.edit': 'Edit product kits',
  'kits.delete': 'Delete product kits'
}

export const PERMISSION_GROUPS: Record<string, string[]> = {
  system: ['admin.access', 'roles.manage'],
  dashboard: ['dashboard.view'],
  products: ['products.view', 'products.create', 'products.edit', 'products.delete', 'products.viewCostPrice'],
  brands: ['brands.view', 'brands.create', 'brands.edit', 'brands.delete'],
  productTaxonomy: ['productTaxonomy.view', 'productTaxonomy.manage'],
  presentations: ['presentations.view', 'presentations.edit', 'presentations.publish'],
  campaigns: ['campaigns.view', 'campaigns.create', 'campaigns.edit', 'campaigns.delete'],
  kits: ['kits.view', 'kits.create', 'kits.edit', 'kits.delete'],
  distributors: ['distributors.view', 'distributors.create', 'distributors.edit', 'distributors.delete'],
  inventory: ['inventory.view', 'inventory.transfer'],
  pharmacies: ['pharmacies.view', 'pharmacies.create', 'pharmacies.edit', 'pharmacies.delete'],
  doctors: ['doctors.view', 'doctors.create', 'doctors.edit', 'doctors.delete', 'doctors.assign'],
  doctorLocations: ['doctorLocations.review'],
  orders: ['orders.view', 'orders.create', 'orders.edit', 'orders.deliver', 'orders.return'],
  /** Finance menu & accounting — mirrors web Finance navigation permissions. */
  finance: [
    'payments.view',
    'payments.create',
    'ledger.view',
    'accounts.view',
    'accounts.manage',
    'vouchers.view',
    'vouchers.transfer',
    'vouchers.create',
    'vouchers.post',
    'vouchers.reverse',
    'reports.accounting'
  ],
  targets: ['targets.view', 'targets.create', 'targets.edit'],
  weeklyPlans: [
    'weeklyPlans.view',
    'weeklyPlans.create',
    'weeklyPlans.edit',
    'weeklyPlans.markVisit',
    'weeklyPlans.review',
    'weeklyPlans.approve'
  ],
  callPoints: ['callPoints.view', 'callPoints.create', 'callPoints.edit', 'callPoints.delete'],
  expenses: [
    'expenses.view',
    'expenses.create',
    'expenses.edit',
    'expenses.delete',
    'expenses.approve',
    'expenses.reject'
  ],
  payroll: ['payroll.view', 'payroll.create', 'payroll.edit', 'payroll.pay'],
  attendance: [
    'attendance.view',
    'attendance.viewTeam',
    'attendance.mark',
    'attendance.request.create',
    'attendance.approve',
    'attendance.approve.direct',
    'attendance.approve.escalated',
    'attendance.viewEscalations',
    'attendance.override',
    'attendance.matrix.manage',
    'attendance.governance.view'
  ],
  reports: ['reports.view'],
  suppliers: ['suppliers.view', 'suppliers.manage'],
  procurement: [
    'procurement.view',
    'procurement.create',
    'procurement.approve',
    'procurement.receive',
    'procurement.invoicePost',
    'procurement.return',
    'procurement.grnReverse',
    'procurement.cancelPo'
  ],
  users: ['users.view', 'users.create', 'users.edit', 'users.delete'],
  team: ['team.view', 'team.manage', 'team.viewAllReports'],
  territories: ['territories.view', 'territories.manage'],
  deviceControl: ['deviceControl.manage']
}

export const ALL_PERMISSIONS: string[] = Object.values(PERMISSION_GROUPS).flat()
export const DASHBOARD_VIEW = 'dashboard.view'

export const labelFor = (perm: string) => PERMISSION_LABELS[perm] ?? perm.split('.').slice(1).join(' · ')
