'use client'

import type { ReactNode } from 'react'
import Box from '@mui/material/Box'
import Container from '@mui/material/Container'
import Divider from '@mui/material/Divider'
import Link from '@mui/material/Link'
import Stack from '@mui/material/Stack'
import Typography from '@mui/material/Typography'
import { alpha, useTheme } from '@mui/material/styles'
import NextLink from 'next/link'

import Logo from '@components/layout/shared/Logo'
import { privacyContact } from '@/configs/privacyContact'

type Section = {
  id: string
  title: string
  body: ReactNode
}

function P({ children }: { children: ReactNode }) {
  return (
    <Typography
      component='p'
      variant='body1'
      color='text.secondary'
      sx={{
        mb: { xs: 1.5, md: 2 },
        fontSize: { xs: '0.9375rem', md: '1rem' },
        lineHeight: { xs: 1.7, md: 1.75 }
      }}
    >
      {children}
    </Typography>
  )
}

function BulletList({ items }: { items: string[] }) {
  return (
    <Box
      component='ul'
      className='mbs-0 mbe-4 mis-0 mie-0 ps-6 md:ps-8'
      sx={{ color: 'text.secondary', listStyleType: 'disc', listStylePosition: 'outside' }}
    >
      {items.map(item => (
        <Typography
          component='li'
          variant='body1'
          key={item}
          className='mbe-2'
          sx={{
            fontSize: { xs: '0.9375rem', md: '1rem' },
            lineHeight: { xs: 1.65, md: 1.7 },
            paddingInlineStart: '0.25rem'
          }}
        >
          {item}
        </Typography>
      ))}
    </Box>
  )
}

const PrivacyPolicyPage = () => {
  const theme = useTheme()
  const { developerName, productName, supportEmail, website, address, effectiveDate, lastUpdated } =
    privacyContact

  const sections: Section[] = [
    {
      id: 'introduction',
      title: '1. Introduction',
      body: (
        <>
          <P>
            PharmaERP (“PharmaERP”, “we”, “us”, or “our”) is a multi-tenant pharmaceutical distribution and
            field-force execution platform. It includes a web application for administrators and managers and a
            mobile application for medical representatives and field teams.
          </P>
          <P>
            This Privacy Policy explains what information PharmaERP collects, how it is used, who can access it,
            and the choices available to users. It is written to reflect the current product behaviour of the web
            app, mobile app, and backend API.
          </P>
          <P>
            PharmaERP is an enterprise / B2B product. Accounts are created for employees and authorized users of
            customer organizations (“Customer Organizations”). Customer Organizations control much of the business
            data entered into their tenant.
          </P>
        </>
      )
    },
    {
      id: 'scope',
      title: '2. Scope',
      body: (
        <>
          <P>This Policy applies to:</P>
          <BulletList
            items={[
              'The PharmaERP web application',
              'The PharmaERP Mobile application (Android / iOS)',
              'Related backend APIs and optional media storage used by those applications'
            ]}
          />
          <P>
            It does not apply to third-party websites or apps that we do not operate (for example, Google Maps when
            opened outside PharmaERP), except where we describe how PharmaERP uses those services.
          </P>
        </>
      )
    },
    {
      id: 'information-we-collect',
      title: '3. Information We Collect',
      body: (
        <>
          <P>We collect information in three ways:</P>
          <BulletList
            items={[
              'Information you or your organization provide (account setup, CRM records, orders, plans)',
              'Information collected automatically from devices (location during field work, device identifiers, app diagnostics related to tracking)',
              'Information generated by product use (attendance events, visit logs, audit logs, sync and notification status)'
            ]}
          />
          <P>
            PharmaERP does not operate a consumer social network and does not sell personal information.
          </P>
        </>
      )
    },
    {
      id: 'personal-information',
      title: '4. Personal Information',
      body: (
        <>
          <P>For authorized users (employees / field staff), we typically process:</P>
          <BulletList
            items={[
              'Name, work email address, and phone number (if provided)',
              'Password (stored as a one-way hash; never returned by the API)',
              'Role, permissions, manager hierarchy, and territory assignments',
              'Login metadata such as last login time and last login IP address',
              'Optional profile photo / avatar when media upload is enabled',
              'Employment-related operational data such as attendance, expenses, and payroll records managed by your organization'
            ]}
          />
          <P>
            Authentication uses JSON Web Tokens (access and refresh tokens). On the web app, tokens are stored in
            browser local storage. On the mobile app, tokens and a device identifier are stored in the device
            secure store (Keychain / Keystore).
          </P>
        </>
      )
    },
    {
      id: 'location-information',
      title: '5. Location Information',
      body: (
        <>
          <P>
            Location is central to field-force features. PharmaERP requests location permission only for
            operational purposes described below. Precise location is collected when the relevant feature is used
            and when your organization’s configuration enables it.
          </P>
          <Typography variant='subtitle1' fontWeight={600} sx={{ mb: 1, mt: 1 }}>
            Foreground location
          </Typography>
          <P>
            While you use the mobile app, PharmaERP may read your current location to validate attendance
            check-in / check-out, verify visits near doctor or call-point coordinates, and show maps. Check-in and
            check-out records may store latitude, longitude, and GPS accuracy.
          </P>
          <Typography variant='subtitle1' fontWeight={600} sx={{ mb: 1, mt: 1 }}>
            Background location and live tracking
          </Typography>
          <P>
            If your organization enables live tracking / manager live map features, the mobile app may continue to
            collect location while you are checked in, including when the app is in the background. On Android this
            uses a foreground service notification; on iOS it may require “Always” location permission. Location
            updates are intended to stop when you check out. Managers with appropriate permissions can see your
            last known position on the live tracking screen (not a continuous video feed).
          </P>
          <P>
            Before background sharing is enabled, the mobile app presents an in-app consent explanation. You can
            revoke background location access in your device settings at any time; doing so may limit attendance or
            live-tracking features required by your employer.
          </P>
          <Typography variant='subtitle1' fontWeight={600} sx={{ mb: 1, mt: 1 }}>
            What location samples include
          </Typography>
          <P>
            Live-tracking heartbeats may include latitude, longitude, accuracy, optional speed and heading, capture
            time, whether the sample came from foreground or background, optional battery percentage, and a client
            identifier used for reliable sync. Samples may be quality-filtered (for example, low-accuracy points may
            be kept for route history but not shown as the live pin).
          </P>
          <Typography variant='subtitle1' fontWeight={600} sx={{ mb: 1, mt: 1 }}>
            Attendance validation, route history, and check-in verification
          </Typography>
          <BulletList
            items={[
              'Attendance validation: distance from a configured check-in point, call point, or policy radius may be evaluated and stored with the attendance record.',
              'Visit verification: when a doctor location is verified, visit completion may record distance from that location and a geofence result (inside / outside / not applicable).',
              'Route history: historical heartbeat trails may be shown to authorized managers for a selected day or period, including replay on maps.',
              'Territories and geofences: organizations may configure territory boundaries, call points, and geofence-related map features.'
            ]}
          />
        </>
      )
    },
    {
      id: 'device-information',
      title: '6. Device Information',
      body: (
        <>
          <P>The mobile app collects device information needed for security and operations:</P>
          <BulletList
            items={[
              'A stable device identifier generated on first launch',
              'Platform (iOS / Android), brand, model, OS version, and app version',
              'Optional Expo push notification token when notifications are enabled',
              'Optional tracking diagnostic events used to analyze GPS / sync gaps (retained on a time-limited basis)'
            ]}
          />
          <P>
            If your organization enables device control, login may be limited to a bound device. Changing devices
            can require an administrator-approved device-change request.
          </P>
        </>
      )
    },
    {
      id: 'business-data',
      title: '7. Business Data',
      body: (
        <>
          <P>
            PharmaERP stores business and operational records entered by Customer Organizations, including orders,
            inventory, deliveries, payments, settlements, ledgers, procurement, targets, weekly and daily plans,
            expenses, announcements, and related reports. This data is processed to provide the ERP and field-force
            services your organization has licensed.
          </P>
        </>
      )
    },
    {
      id: 'doctor-pharmacy-data',
      title: '8. Doctor & Pharmacy Data',
      body: (
        <>
          <P>
            Customer Organizations may store professional contact and CRM data about doctors, pharmacies,
            distributors, and suppliers — for example names, specialty, phone numbers, email addresses, addresses,
            coordinates, territory assignment, visit targets, and professional registration numbers (such as PMDC).
            Doctor records may include an approximate patient count as a number; PharmaERP does not provide a
            patient medical-records module and is not designed to store patient health records.
          </P>
          <P>
            Customer Organizations are responsible for having a lawful basis to collect and use this professional
            contact information in their markets.
          </P>
        </>
      )
    },
    {
      id: 'attendance-data',
      title: '9. Attendance Data',
      body: (
        <>
          <P>Attendance records may include:</P>
          <BulletList
            items={[
              'Check-in and check-out times and sources',
              'Status, late minutes, notes, and approval workflow state',
              'GPS coordinates and accuracy at check-in / check-out',
              'Distance from required check-in location and location-policy metadata',
              'Optional attendance selfie media when your organization enables media upload features'
            ]}
          />
          <P>
            Managers and administrators with the appropriate permissions can view team or company attendance
            according to role-based access controls configured for the tenant.
          </P>
        </>
      )
    },
    {
      id: 'route-history',
      title: '10. Route History',
      body: (
        <>
          <P>
            When live tracking is used, location samples form a historical trail. Authorized managers may view route
            history and replay paths on maps for operational review (coverage, plan execution, and quality of GPS
            samples). Retention of heartbeat data is time-limited (see Data Retention).
          </P>
        </>
      )
    },
    {
      id: 'live-tracking',
      title: '11. Live Tracking',
      body: (
        <>
          <P>
            Live tracking is an organization-configurable feature. When enabled and while a field user is checked
            in, the mobile app periodically sends location heartbeats to PharmaERP servers. Authorized managers can
            view last-known positions on a live map. Heartbeats may also be delivered through an internal realtime
            channel to keep the manager map up to date.
          </P>
          <P>
            Live tracking is not continuous video surveillance. Displayed positions can become stale if the device
            loses connectivity, GPS quality is poor, or permissions are revoked.
          </P>
        </>
      )
    },
    {
      id: 'camera-media',
      title: '12. Camera & Media',
      body: (
        <>
          <P>
            When media features are enabled by configuration, PharmaERP may use the device camera or photo library
            to capture attendance selfies, visit photos, expense receipts, product visuals, and profile images.
            Files are uploaded through the API to object storage (Cloudflare R2 when configured) and referenced as
            media assets linked to the relevant record.
          </P>
          <P>
            The Android build may declare a microphone permission because it is included with the camera SDK. The
            current PharmaERP product flows use the camera for still images / attachments; they are not designed as
            an audio-recording product feature.
          </P>
        </>
      )
    },
    {
      id: 'how-we-use',
      title: '13. How We Use Information',
      body: (
        <>
          <P>We use information to:</P>
          <BulletList
            items={[
              'Authenticate users and enforce role-based access and device-binding policies',
              'Operate ERP workflows (orders, inventory, finance, CRM, planning, visits)',
              'Validate field attendance and visit execution',
              'Provide live tracking and route history to authorized managers when enabled',
              'Sync offline mobile actions when connectivity returns',
              'Send push and in-app notifications when enabled',
              'Maintain audit logs and security records (including IP addresses associated with actions)',
              'Host and deliver media files when media upload is enabled',
              'Improve reliability of location and sync features using limited diagnostic events',
              'Comply with legal obligations and enforce our agreements with Customer Organizations'
            ]}
          />
        </>
      )
    },
    {
      id: 'data-sharing',
      title: '14. Data Sharing',
      body: (
        <>
          <P>We share information only as needed to operate the service:</P>
          <BulletList
            items={[
              'Within a Customer Organization tenant, according to roles and permissions (for example, managers viewing team attendance or live location)',
              'With infrastructure and service providers that process data on our behalf (database hosting, object storage, maps, push delivery, application hosting)',
              'When required by law, regulation, or valid legal process',
              'In connection with a corporate transaction, subject to appropriate safeguards'
            ]}
          />
          <P>We do not sell personal information and do not share it for cross-context advertising.</P>
        </>
      )
    },
    {
      id: 'third-party-services',
      title: '15. Third-Party Services',
      body: (
        <>
          <P>PharmaERP relies on the following categories of third-party services as implemented today:</P>
          <BulletList
            items={[
              'MongoDB Atlas — primary application database (including TTL indexes used for some time-limited collections)',
              'Cloudflare R2 — media object storage (S3-compatible API) when media upload is enabled for the deployment',
              'Google Maps Platform — interactive maps, geocoding, places autocomplete, routing / distance services, and map tiles',
              'Expo — mobile runtime and push notification delivery (Expo Push / related Expo services)',
              'Application hosting providers used to run the API and web application'
            ]}
          />
          <P>
            Redis may be present in the product as an optional infrastructure component (for example, heartbeat rate
            limiting or multi-node realtime fan-out). It is only used when explicitly configured with a Redis
            connection URL. In the current deployment Redis is not configured, so PharmaERP does not send data to a
            Redis service.
          </P>
          <P>
            These providers process data under their own terms and security practices. Map deep links that open the
            Google Maps application or website are subject to Google’s terms.
          </P>
          <P>
            PharmaERP’s current implementation does not integrate consumer advertising SDKs, Stripe payments
            processing, or third-party email/SMS marketing providers as part of the core product stack described in
            this Policy.
          </P>
        </>
      )
    },
    {
      id: 'data-security',
      title: '16. Data Security',
      body: (
        <>
          <P>We apply technical and organizational measures appropriate to an enterprise application, including:</P>
          <BulletList
            items={[
              'Password hashing with bcrypt (via bcryptjs) before passwords are stored',
              'JWT access tokens and refresh tokens for sessions; on mobile, refresh tokens are stored server-side as SHA-256 hashes (the raw refresh token is not kept in the database)',
              'Permission checks on API routes',
              'Tenant (company) scoping of data access',
              'Secure storage of mobile auth secrets on device',
              'Optional device binding to reduce unauthorized device use',
              'Transport of media via authenticated upload flows and short-lived signed access URLs when Cloudflare R2 (or equivalent object storage) is enabled',
              'Application and audit logging for security-relevant actions'
            ]}
          />
          <P>
            No method of transmission or storage is completely secure. Customer Organizations should also apply
            strong password practices, limit admin privileges, and manage employee offboarding promptly.
          </P>
        </>
      )
    },
    {
      id: 'data-retention',
      title: '17. Data Retention',
      body: (
        <>
          <P>Retention depends on data type and organization settings:</P>
          <BulletList
            items={[
              'Live-tracking heartbeats: the active (hot) collection has a MongoDB TTL index of approximately 90 days on capture time. Organization settings (typically 7–365 days) may also archive older samples into a longer-term store used for compliance and route history; that archive collection has no automatic TTL purge in the current product',
              'Tracking diagnostics: MongoDB TTL of approximately 90 days',
              'Media assets: classified as temporary or permanent; temporary media may expire according to company retention settings for check-in, visit, or expense media',
              'Core business records (orders, ledgers, CRM, attendance history): retained for as long as the Customer Organization maintains the tenant and applicable legal/accounting needs require',
              'Soft-deleted records may remain in the database in a deleted state rather than being immediately erased'
            ]}
          />
        </>
      )
    },
    {
      id: 'user-rights',
      title: '18. User Rights',
      body: (
        <>
          <P>
            Depending on your jurisdiction and your relationship with the Customer Organization, you may have rights
            to access, correct, update, restrict, or delete personal information, or to object to certain processing.
          </P>
          <P>
            Because PharmaERP is provided to organizations, many requests should start with your employer or the
            organization’s administrator (who controls user accounts and much of the tenant data). You may also
            contact us using the details in Contact Information. We will coordinate with the relevant Customer
            Organization where appropriate.
          </P>
        </>
      )
    },
    {
      id: 'children',
      title: '19. Children’s Privacy',
      body: (
        <>
          <P>
            PharmaERP is a workplace tool intended for adults acting in a professional capacity. It is not directed
            to children, and we do not knowingly collect personal information from children.
          </P>
        </>
      )
    },
    {
      id: 'international-transfers',
      title: '20. International Transfers',
      body: (
        <>
          <P>
            PharmaERP uses cloud infrastructure and third-party processors (including database hosting, object
            storage, maps, push delivery, and application hosting). Depending on where you and your organization are
            located, personal information may be processed in countries other than your own. Where required, we and
            our Customer Organizations rely on appropriate contractual and technical safeguards for such transfers.
          </P>
        </>
      )
    },
    {
      id: 'cookies-storage',
      title: '21. Cookies and Local Storage',
      body: (
        <>
          <Typography variant='subtitle1' fontWeight={600} sx={{ mb: 1 }}>
            Web application
          </Typography>
          <BulletList
            items={[
              'Local storage: authentication tokens and certain UI/workflow caches (for example visit drafts and map display preferences)',
              'Cookies: theme / layout settings and color preference used by the UI shell',
              'Session storage: limited UI preferences in admin attendance screens'
            ]}
          />
          <Typography variant='subtitle1' fontWeight={600} sx={{ mb: 1, mt: 1 }}>
            Mobile application
          </Typography>
          <BulletList
            items={[
              'Secure store: access token, refresh token, device identifier',
              'SQLite: offline queue (outbox), cached configuration, and offline attendance/visit data for synchronization',
              'AsyncStorage: theme preference'
            ]}
          />
          <P>
            These technologies are used for authentication, offline reliability, and user interface preferences —
            not for third-party advertising.
          </P>
        </>
      )
    },
    {
      id: 'account-deletion',
      title: '22. Account Deletion',
      body: (
        <>
          <P>
            PharmaERP does not currently provide an in-app self-service “Delete my account” button for end users.
            User accounts are managed by Customer Organization administrators. Administrators can deactivate accounts
            so users can no longer sign in while preserving historical business records (such as orders and
            attendance) that the organization needs.
          </P>
          <P>To request deletion or deactivation of your PharmaERP user account:</P>
          <BulletList
            items={[
              'Contact your organization’s PharmaERP administrator first, or',
              `Email ${supportEmail} with the subject “Account deletion request”, your full name, work email used for PharmaERP, and organization name`
            ]}
          />
          <P>
            We will work with the Customer Organization to deactivate the account and address deletion or anonymization
            where legally required and technically feasible, noting that some records may be retained for legitimate
            business, security, or legal reasons.
          </P>
          <P>
            On a device, signing out clears session tokens from secure storage. Uninstalling the app removes local
            caches on that device but does not by itself delete server-side records.
          </P>
        </>
      )
    },
    {
      id: 'changes',
      title: '23. Changes to this Policy',
      body: (
        <>
          <P>
            We may update this Privacy Policy when product behaviour or legal requirements change. The “Last
            updated” date at the top of this page will be revised when changes are published. Material changes may
            also be communicated through the product or to Customer Organization administrators.
          </P>
        </>
      )
    },
    {
      id: 'contact',
      title: '24. Contact Information',
      body: (
        <>
          <P>Questions about this Privacy Policy or PharmaERP privacy practices can be directed to:</P>
          <Box
            component='address'
            className='p-5 sm:p-6 mbe-4'
            sx={{
              fontStyle: 'normal',
              borderRadius: { xs: 1.5, md: 2 },
              border: theme => `1px solid ${theme.palette.divider}`,
              bgcolor: theme => alpha(theme.palette.primary.main, theme.palette.mode === 'dark' ? 0.08 : 0.04),
              wordBreak: 'break-word'
            }}
          >
            <Typography variant='body2' color='text.secondary' sx={{ mb: 0.5 }}>
              Developer / Operator
            </Typography>
            <Typography variant='body1' fontWeight={600} sx={{ mb: 1.5 }}>
              {developerName}
            </Typography>
            <Typography variant='body2' color='text.secondary' sx={{ mb: 0.5 }}>
              Product: {productName}
            </Typography>
            <Typography variant='body2' color='text.secondary' sx={{ mb: 0.5 }}>
              Support email:{' '}
              <Link href={`mailto:${supportEmail}`} underline='hover'>
                {supportEmail}
              </Link>
            </Typography>
            <Typography variant='body2' color='text.secondary' sx={{ mb: 0.5 }}>
              Website:{' '}
              <Link href={website} target='_blank' rel='noopener noreferrer' underline='hover'>
                {website}
              </Link>
            </Typography>
            <Typography variant='body2' color='text.secondary'>
              Address: {address}
            </Typography>
          </Box>
        </>
      )
    }
  ]

  return (
    <Box
      component='main'
      sx={{
        minHeight: '100dvh',
        bgcolor: 'background.default',
        color: 'text.primary',
        pb: 'env(safe-area-inset-bottom)'
      }}
    >
      <Box
        component='header'
        className='sticky top-0'
        sx={{
          borderBottom: theme => `1px solid ${theme.palette.divider}`,
          bgcolor: 'background.paper',
          zIndex: theme.zIndex.appBar,
          paddingBlockStart: 'env(safe-area-inset-top, 0px)'
        }}
      >
        <Container maxWidth='md' disableGutters className='flex items-center justify-between gap-3 px-5 py-4 sm:px-6 sm:py-5'>
          <Link
            component={NextLink}
            href='/login'
            underline='none'
            aria-label='PharmaERP home'
            className='flex min-is-0 items-center'
          >
            <Logo />
          </Link>
          <Link
            component={NextLink}
            href='/login'
            variant='body2'
            underline='hover'
            color='primary'
            className='shrink-0 px-1 py-2'
          >
            Sign in
          </Link>
        </Container>
      </Box>

      <Container maxWidth='md' disableGutters className='px-5 py-6 sm:px-6 sm:py-8 md:py-10'>
        <Stack spacing={1} className='mbe-6 md:mbe-8'>
          <Typography
            component='h1'
            variant='h3'
            fontWeight={700}
            sx={{
              fontSize: { xs: '1.75rem', sm: '2.125rem', md: '3rem' },
              lineHeight: { xs: 1.25, md: 1.2 },
              letterSpacing: { xs: '-0.02em', md: 'normal' }
            }}
          >
            Privacy Policy
          </Typography>
          <Typography variant='body2' color='text.secondary' sx={{ fontSize: { xs: '0.8125rem', md: '0.875rem' } }}>
            PharmaERP web and mobile applications
          </Typography>
          <Typography
            variant='body2'
            color='text.secondary'
            className='flex flex-col gap-1 sm:flex-row sm:items-center'
            sx={{ fontSize: { xs: '0.8125rem', md: '0.875rem' } }}
          >
            <span>Effective date: {effectiveDate}</span>
            <Box component='span' className='hidden sm:inline mie-2 mis-2' aria-hidden>
              ·
            </Box>
            <span>Last updated: {lastUpdated}</span>
          </Typography>
        </Stack>

        <Box
          component='nav'
          aria-label='Privacy Policy sections'
          className='p-5 sm:p-6 mbe-6 md:mbe-8'
          sx={{
            borderRadius: { xs: 1.5, md: 2 },
            border: theme => `1px solid ${theme.palette.divider}`,
            bgcolor: 'background.paper'
          }}
        >
          <Typography variant='subtitle2' fontWeight={700} className='mbe-3'>
            Contents
          </Typography>
          <Box
            component='ol'
            className='m-0 ps-6 sm:ps-7'
            sx={{
              listStyleType: 'decimal',
              listStylePosition: 'outside',
              columns: { xs: 1, sm: 2 },
              columnGap: { sm: 3, md: 4 }
            }}
          >
            {sections.map(section => (
              <Typography
                component='li'
                variant='body2'
                key={section.id}
                className='mbe-2'
                sx={{
                  breakInside: 'avoid',
                  lineHeight: 1.5,
                  paddingInlineStart: '0.35rem'
                }}
              >
                <Link
                  href={`#${section.id}`}
                  underline='hover'
                  color='primary'
                  className='inline-block py-1'
                  sx={{ fontSize: { xs: '0.8125rem', md: '0.875rem' } }}
                >
                  {section.title.replace(/^\d+\.\s*/, '')}
                </Link>
              </Typography>
            ))}
          </Box>
        </Box>

        <Stack component='article' spacing={0} divider={<Divider flexItem className='my-2 md:my-3' />}>
          {sections.map(section => (
            <Box
              key={section.id}
              component='section'
              id={section.id}
              aria-labelledby={`${section.id}-heading`}
              className='py-5 md:py-6'
              sx={{ scrollMarginTop: { xs: 88, md: 104 } }}
            >
              <Typography
                component='h2'
                id={`${section.id}-heading`}
                variant='h5'
                fontWeight={700}
                className='mbe-3 md:mbe-4'
                sx={{
                  fontSize: { xs: '1.125rem', sm: '1.25rem', md: '1.5rem' },
                  lineHeight: 1.35
                }}
              >
                {section.title}
              </Typography>
              {section.body}
            </Box>
          ))}
        </Stack>

        <Divider className='my-6 md:my-8' />

        <Stack
          component='footer'
          direction={{ xs: 'column', sm: 'row' }}
          spacing={2}
          justifyContent='space-between'
          alignItems={{ xs: 'flex-start', sm: 'center' }}
          className='pbe-4'
        >
          <Typography variant='caption' color='text.secondary' sx={{ lineHeight: 1.5 }}>
            © {new Date().getFullYear()} PharmaERP. All rights reserved.
          </Typography>
          <Stack direction='row' spacing={3} className='flex-wrap'>
            <Link
              component={NextLink}
              href='/privacy'
              variant='caption'
              underline='hover'
              color='text.secondary'
              className='py-1'
            >
              Privacy Policy
            </Link>
            <Link
              component={NextLink}
              href='/login'
              variant='caption'
              underline='hover'
              color='text.secondary'
              className='py-1'
            >
              Sign in
            </Link>
          </Stack>
        </Stack>
      </Container>
    </Box>
  )
}

export default PrivacyPolicyPage
